import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { api } from "@/utils/api";

const Home: NextPage = () => {
  const user = useUser();

  const { data } = api.posts.getAll.useQuery();
  console.log(data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {!user.isSignedIn && <SignInButton />}
        {user.isSignedIn && <SignOutButton />}

        <div>
          {data?.map((post) => (
            <div key={post.id}>
              <h1>{post.content}</h1>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
